name: Build, test and publish

on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install meson, SDL, etc.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build libsdl2-dev libsdl2-2.0-0 libpcap0.8-dev
          sudo pip3 install meson
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Run cargo test
        run: cargo test

  build_linux:
    runs-on: ubuntu-latest
    name: Build Linux
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install meson, SDL, etc.
        run: |
          sudo apt-get update
          sudo apt-get install python3 python3-pip python3-setuptools python3-wheel ninja-build libsdl2-dev libsdl2-2.0-0 libpcap0.8-dev
          sudo pip3 install meson
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
  build_macos_windows:
    runs-on: ${{ matrix.os }}
    name: Build Mac/Windows
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-2019
            target: i686-pc-windows-msvc
          - os: windows-2019
            target: x86_64-pc-windows-msvc
          - os: macos-11
            target: x86_64-apple-darwin
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install MacOS build deps
        if: matrix.os == 'macos-11'
        run: |
          brew install coreutils gcc sdl2 meson glib
      - name: Add msbuild to PATH
        if: matrix.os == 'windows-2019'
        uses: microsoft/setup-msbuild@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          default: true
      - name: Build
        run: cargo build --release
        env:
          TARGET: ${{ matrix.target }}
          FASTBUILD: "1"
